title: Kenny's homepage
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Haodong Duan # add your name
author-nick: Kenny
author-img: kennymckormick.png # add your photo
about-author: |+
    First year MPhil student @ CUHK. Working on computer vision.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: kennymckormick # add your Github handle
# social-linkedin: # add your Linkedin handle
social-email: dhd.efz@gmail.com # add your Email address


menu:
  - text: Portfolio
    link: /tags
    icon: ""

  # - text: Publication
  #   link: /publication
  #   icon: ""

  - text: Resume
    link: /assets/files/resume_0117.pdf
    icon: ""

  - text: About ME
    link: /about
    icon: ""

  - text: Home
    link: /
    icon: ""



# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
